
-- Create the unified fact table for search term performance
CREATE TABLE relatorio_google_fact_search_term_performance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    cliente_id UUID NOT NULL REFERENCES relatorio_clientes_bf_labs(id),
    campaign_id BIGINT NOT NULL REFERENCES relatorio_google_dim_campaigns(id),
    keyword_id BIGINT REFERENCES relatorio_google_dim_keywords(id),
    search_term_id BIGINT REFERENCES relatorio_google_dim_search_terms(id),
    clicks INTEGER DEFAULT 0,
    impressions INTEGER DEFAULT 0,
    cost NUMERIC DEFAULT 0,
    conversions NUMERIC DEFAULT 0,
    ctr NUMERIC DEFAULT 0,
    average_cpc NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- Add comments
COMMENT ON TABLE relatorio_google_fact_search_term_performance IS 'Unified fact table for Google Ads performance at search term granularity';
COMMENT ON COLUMN relatorio_google_fact_search_term_performance.keyword_id IS 'Optional FK - null for campaign-level aggregates';
COMMENT ON COLUMN relatorio_google_fact_search_term_performance.search_term_id IS 'Optional FK - null for keyword-level aggregates';

-- Create indexes for common query patterns
CREATE INDEX idx_fact_performance_cliente_date 
ON relatorio_google_fact_search_term_performance(cliente_id, date);

CREATE INDEX idx_fact_performance_campaign 
ON relatorio_google_fact_search_term_performance(campaign_id);

CREATE INDEX idx_fact_performance_keyword 
ON relatorio_google_fact_search_term_performance(keyword_id);

CREATE INDEX idx_fact_performance_search_term 
ON relatorio_google_fact_search_term_performance(search_term_id);

-- Composite index for drill-down queries
CREATE INDEX idx_fact_performance_drill_down 
ON relatorio_google_fact_search_term_performance(cliente_id, date, campaign_id, keyword_id, search_term_id);
;
