
-- Drop the unnecessary adset/ad tables (payload is campaign-level only)
DROP TABLE IF EXISTS relatorio_meta_fact_performance CASCADE;
DROP TABLE IF EXISTS relatorio_meta_dim_ads CASCADE;
DROP TABLE IF EXISTS relatorio_meta_dim_adsets CASCADE;
DROP TABLE IF EXISTS relatorio_meta_dim_campaigns CASCADE;

-- Create simplified dim_campaigns
CREATE TABLE relatorio_meta_dim_campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id UUID NOT NULL REFERENCES relatorio_clientes_bf_labs(id),
    campaign_id_meta TEXT NOT NULL,
    campaign_name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(cliente_id, campaign_id_meta)
);

-- Create fact table matching the exact payload structure
CREATE TABLE relatorio_meta_fact_campaign_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    cliente_id UUID NOT NULL REFERENCES relatorio_clientes_bf_labs(id),
    campaign_id BIGINT NOT NULL REFERENCES relatorio_meta_dim_campaigns(id),
    
    -- Spend & Cost metrics
    spend NUMERIC DEFAULT 0,
    cpm NUMERIC DEFAULT 0,
    cpp NUMERIC DEFAULT 0,
    ctr NUMERIC DEFAULT 0,
    cpc NUMERIC DEFAULT 0,
    cpl NUMERIC DEFAULT 0,
    cost_per_conversation NUMERIC DEFAULT 0,
    
    -- Click metrics
    link_clicks INTEGER DEFAULT 0,
    outbound_clicks INTEGER DEFAULT 0,
    
    -- Conversion metrics
    leads INTEGER DEFAULT 0,
    conversations INTEGER DEFAULT 0,
    messaging_connections INTEGER DEFAULT 0,
    depth2_messages INTEGER DEFAULT 0,
    depth3_messages INTEGER DEFAULT 0,
    first_replies INTEGER DEFAULT 0,
    
    -- Engagement metrics
    follows INTEGER DEFAULT 0,
    post_engagements INTEGER DEFAULT 0,
    page_engagements INTEGER DEFAULT 0,
    reactions INTEGER DEFAULT 0,
    saves INTEGER DEFAULT 0,
    comments INTEGER DEFAULT 0,
    shares INTEGER DEFAULT 0,
    posts INTEGER DEFAULT 0,
    
    -- Video metrics
    video_views INTEGER DEFAULT 0,
    video_p50 NUMERIC DEFAULT 0,
    video_p95 NUMERIC DEFAULT 0,
    video_avg_time NUMERIC DEFAULT 0,
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_meta_fact_campaign_cliente_date ON relatorio_meta_fact_campaign_daily(cliente_id, date);
CREATE INDEX idx_meta_fact_campaign_campaign ON relatorio_meta_fact_campaign_daily(campaign_id);

-- RLS
ALTER TABLE relatorio_meta_dim_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE relatorio_meta_fact_campaign_daily ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Allow anon all on meta dim campaigns" ON relatorio_meta_dim_campaigns FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon all on meta fact campaign" ON relatorio_meta_fact_campaign_daily FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow auth read meta dim" ON relatorio_meta_dim_campaigns FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow auth read meta fact" ON relatorio_meta_fact_campaign_daily FOR SELECT TO authenticated USING (true);
;
