
-- 1. Dimension Tables

CREATE TABLE IF NOT EXISTS relatorio_meta_dim_campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id UUID NOT NULL REFERENCES relatorio_clientes_bf_labs(id),
    campaign_id_meta TEXT NOT NULL,
    campaign_name TEXT NOT NULL,
    status TEXT,
    objective TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(cliente_id, campaign_id_meta)
);

CREATE TABLE IF NOT EXISTS relatorio_meta_dim_adsets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id UUID NOT NULL REFERENCES relatorio_clientes_bf_labs(id),
    campaign_id BIGINT NOT NULL REFERENCES relatorio_meta_dim_campaigns(id),
    adset_id_meta TEXT NOT NULL,
    adset_name TEXT NOT NULL,
    status TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(cliente_id, adset_id_meta)
);

CREATE TABLE IF NOT EXISTS relatorio_meta_dim_ads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id UUID NOT NULL REFERENCES relatorio_clientes_bf_labs(id),
    adset_id BIGINT NOT NULL REFERENCES relatorio_meta_dim_adsets(id),
    ad_id_meta TEXT NOT NULL,
    ad_name TEXT NOT NULL,
    status TEXT,
    creative_type TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(cliente_id, ad_id_meta)
);

-- 2. Fact Table

CREATE TABLE IF NOT EXISTS relatorio_meta_fact_performance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    cliente_id UUID NOT NULL REFERENCES relatorio_clientes_bf_labs(id),
    campaign_id BIGINT NOT NULL REFERENCES relatorio_meta_dim_campaigns(id),
    adset_id BIGINT REFERENCES relatorio_meta_dim_adsets(id),
    ad_id BIGINT REFERENCES relatorio_meta_dim_ads(id),
    
    -- Metrics
    cost NUMERIC DEFAULT 0,
    impressions INTEGER DEFAULT 0,
    clicks INTEGER DEFAULT 0,
    conversions NUMERIC DEFAULT 0,
    leads INTEGER DEFAULT 0,
    
    -- Derived metrics can be calculated on read, but storing raw is fine
    ctr NUMERIC DEFAULT 0,
    cpc NUMERIC DEFAULT 0,
    cpm NUMERIC DEFAULT 0,
    
    -- Extra metrics (JSONB for flexibility)
    metadata JSONB DEFAULT '{}'::jsonb,
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_meta_fact_cliente_date ON relatorio_meta_fact_performance(cliente_id, date);
CREATE INDEX IF NOT EXISTS idx_meta_fact_campaign ON relatorio_meta_fact_performance(campaign_id);
CREATE INDEX IF NOT EXISTS idx_meta_fact_adset ON relatorio_meta_fact_performance(adset_id);
CREATE INDEX IF NOT EXISTS idx_meta_fact_ad ON relatorio_meta_fact_performance(ad_id);

-- RLS Policies
ALTER TABLE relatorio_meta_dim_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE relatorio_meta_dim_adsets ENABLE ROW LEVEL SECURITY;
ALTER TABLE relatorio_meta_dim_ads ENABLE ROW LEVEL SECURITY;
ALTER TABLE relatorio_meta_fact_performance ENABLE ROW LEVEL SECURITY;

-- Allow anon insert for webhook usage (same pattern as Google)
CREATE POLICY "Allow anon insert meta dims" ON relatorio_meta_dim_campaigns FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon select meta dims" ON relatorio_meta_dim_campaigns FOR SELECT TO anon USING (true);
-- (Repeating for others simplified for brevity, in prod act accordingly)

CREATE POLICY "Allow anon insert meta adsets" ON relatorio_meta_dim_adsets FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon select meta adsets" ON relatorio_meta_dim_adsets FOR SELECT TO anon USING (true);

CREATE POLICY "Allow anon insert meta ads" ON relatorio_meta_dim_ads FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon select meta ads" ON relatorio_meta_dim_ads FOR SELECT TO anon USING (true);

CREATE POLICY "Allow anon insert meta facts" ON relatorio_meta_fact_performance FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon select meta facts" ON relatorio_meta_fact_performance FOR SELECT TO anon USING (true);

-- Allow authenticated read
CREATE POLICY "Allow auth read meta facts" ON relatorio_meta_fact_performance FOR SELECT TO authenticated USING (true);
;
