CREATE TABLE IF NOT EXISTS participantes_grupos_wpp_bf (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT REFERENCES grupos_bf_wpp(id) ON DELETE CASCADE,
  phone TEXT NOT NULL,
  nome TEXT,
  is_admin BOOLEAN DEFAULT FALSE,
  baixado_em TIMESTAMPTZ DEFAULT NOW(),
  atualizado_em TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_participantes_group_phone
  ON participantes_grupos_wpp_bf(group_id, phone);

CREATE INDEX IF NOT EXISTS idx_participantes_group
  ON participantes_grupos_wpp_bf(group_id);;
