
-- Drop existing simplified tables
DROP TABLE IF EXISTS relatorio_meta_fact_campaign_daily CASCADE;
DROP TABLE IF EXISTS relatorio_meta_dim_campaigns CASCADE;

-- 1. Dimension: Campaigns
CREATE TABLE relatorio_meta_dim_campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id UUID NOT NULL REFERENCES relatorio_clientes_bf_labs(id),
    campaign_id_meta TEXT NOT NULL,
    campaign_name TEXT NOT NULL,
    objective TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(cliente_id, campaign_id_meta)
);

-- 2. Dimension: AdSets
CREATE TABLE relatorio_meta_dim_adsets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id UUID NOT NULL REFERENCES relatorio_clientes_bf_labs(id),
    campaign_id BIGINT NOT NULL REFERENCES relatorio_meta_dim_campaigns(id),
    adset_id_meta TEXT NOT NULL,
    adset_name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(cliente_id, adset_id_meta)
);

-- 3. Dimension: Ads
CREATE TABLE relatorio_meta_dim_ads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id UUID NOT NULL REFERENCES relatorio_clientes_bf_labs(id),
    adset_id BIGINT NOT NULL REFERENCES relatorio_meta_dim_adsets(id),
    ad_id_meta TEXT NOT NULL,
    ad_name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(cliente_id, ad_id_meta)
);

-- 4. Fact Table: Ad Performance Daily
CREATE TABLE relatorio_meta_fact_ad_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    cliente_id UUID NOT NULL REFERENCES relatorio_clientes_bf_labs(id),
    campaign_id BIGINT NOT NULL REFERENCES relatorio_meta_dim_campaigns(id),
    adset_id BIGINT NOT NULL REFERENCES relatorio_meta_dim_adsets(id),
    ad_id BIGINT NOT NULL REFERENCES relatorio_meta_dim_ads(id),
    
    -- Core metrics
    spend NUMERIC DEFAULT 0,
    impressions INTEGER DEFAULT 0,
    reach INTEGER DEFAULT 0,
    frequency NUMERIC DEFAULT 0,
    clicks INTEGER DEFAULT 0,
    unique_clicks INTEGER DEFAULT 0,
    ctr NUMERIC DEFAULT 0,
    cpc NUMERIC DEFAULT 0,
    cpm NUMERIC DEFAULT 0,
    cpp NUMERIC DEFAULT 0,
    
    -- Action metrics (extracted from actions array)
    link_clicks INTEGER DEFAULT 0,
    page_engagements INTEGER DEFAULT 0,
    post_engagements INTEGER DEFAULT 0,
    video_views INTEGER DEFAULT 0,
    reactions INTEGER DEFAULT 0,
    saves INTEGER DEFAULT 0,
    comments INTEGER DEFAULT 0,
    shares INTEGER DEFAULT 0,
    messaging_conversations INTEGER DEFAULT 0,
    messaging_first_replies INTEGER DEFAULT 0,
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_meta_fact_ad_cliente_date ON relatorio_meta_fact_ad_daily(cliente_id, date);
CREATE INDEX idx_meta_fact_ad_campaign ON relatorio_meta_fact_ad_daily(campaign_id);
CREATE INDEX idx_meta_fact_ad_adset ON relatorio_meta_fact_ad_daily(adset_id);
CREATE INDEX idx_meta_fact_ad_ad ON relatorio_meta_fact_ad_daily(ad_id);

-- RLS
ALTER TABLE relatorio_meta_dim_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE relatorio_meta_dim_adsets ENABLE ROW LEVEL SECURITY;
ALTER TABLE relatorio_meta_dim_ads ENABLE ROW LEVEL SECURITY;
ALTER TABLE relatorio_meta_fact_ad_daily ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "anon_all_meta_dim_campaigns" ON relatorio_meta_dim_campaigns FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon_all_meta_dim_adsets" ON relatorio_meta_dim_adsets FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon_all_meta_dim_ads" ON relatorio_meta_dim_ads FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon_all_meta_fact_ad" ON relatorio_meta_fact_ad_daily FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "auth_read_meta_fact" ON relatorio_meta_fact_ad_daily FOR SELECT TO authenticated USING (true);
;
